[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "scrapy>=2.13.0",
    "selenium>=4.32.0",
    "streamlit>=1.45.1",
    "webdriver-manager>=4.0.2",
]
